### ISSUE TITLE
Request for `am` crate name

### ISSUE THREAD

**Issue by ryanccn** [ryanccn/am#8]
Hey @ajaxm, I’d really like to publish this project with the name as-is on crates.io as `am`! I see that you already own that crate, but it doesn’t contain any code and hasn’t been updated in four years, so I was wondering if you could be so kind as to transfer the crate’s ownership to me or delete the original crate. Thanks :)

**Comment by ryanccn** [comment]
@ajaxm Hello?

**Comment by ajaxm** [comment]
Hi, sorry I missed these! I haven't been maintaining this email. Will look
at this and transfer/delete asap

**Comment by ajaxm** [comment]
Sent an invite via crates.io to add you as an owner under this username (@ryanccn). Thanks for your patience, and lmk when the invite comes through and you're in so I can remove myself

**Comment by ryanccn** [comment]
@ajaxm I've accepted the owner invite, thank you so much!
